version: '2'
services:
  scoreboard:
    build: scoreboard/
    ports:
      - "80:80"
      - "22000:22"
    container_name: scoreboard
  client:
    build: client/
    ports:
      - "22"
    links:
      - scoreboard
    depends_on:
      - scoreboard
